### ISSUE TITLE
Support for pagination on Flight Offers Search?

### ISSUE THREAD

**Issue by moneill** [amadeus4dev/amadeus-open-api-specification#57]
Hi there!

I'm testing out the `/v2/shopping/flight-offers` endpoint with a specific search that _most likely_ returns >250 results. (I'm suspicious because the response is exactly 250 results and doesn't include a particular outbound/return flight combo I know exists.) Since the maximum value for the `max` attribute is `250`, is there any way to obtain additional results or paginate through the full resultset via multiple API calls?

Here's my sample call:

```
curl "https://test.api.amadeus.com/v2/shopping/flight-offers?originLocationCode=LGA&destinationLocationCode=DFW&departureDate=2023-05-23&adults=1&currencyCode=USD&includedAirlineCodes=DL&returnDate=2023-05-30&max=250" \
     -H 'Authorization: Bearer <REDACTED>' \
     -H 'Content-Type: application/x-www-form-urlencoded; charset=utf-8'"
```

Thank you!

**Comment by moneill** [comment]
A related question I'll tack on here -- is there a way to exclude certain fare classes from results, like Basic Economy? When I use `travelClass=ECONOMY` my results are generally all Basic Economy fares.

**Comment by jangamvk** [comment]
Hi  I was looking for a amadeus MPTB response solution, We work on the multiple PCC module , each PCC is taking approx 19 sec to response , which doesn't  meet the business requirement. How do we handle it?

**Comment by tsolakoua** [comment]
Pagination is not supported by the Flight Offers Search. For further questions related to Self-Service APIs please get in touch with the [dedicated support channels](https://developers.amadeus.com/support). For anything related to Enterprise get in touch with your account managers.
